os:
- linux
- osx
- windows
language: node_js
install:
- npm install
node_js:
- "6"
- "7"
- "8"
- "9"
- "10"

jobs:
  include:
  - stage: npm release
    node_js: '8'
    skip_cleanup: true
    deploy:
      provider: npm
      email: nenshou.sora@gmail.com
      api_key: ${NPM_API_TOKEN}
      on:
        branch: /^v[0-9]+\.[0-9]+\.[0-9]+(\-[a-zA-Z0-9]+)*$/
        repo: XC-/npm-linkDependencies
